import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@parkhunt/ui/dist/style.css'
import { ApolloProvider, authOptions } from '@parkhunt/network'
import { SessionProvider } from '@/components/session-provider'
import { Header } from '@parkhunt/ui'
import { useSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ApolloProvider>
        <SessionProvider>
          <body className={inter.className}>{children}</body>
        </SessionProvider>
      </ApolloProvider>
    </html>
  )
}
